name: update docs data.json

on:
  push:
    paths:
      - public/docs/*

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYaml
    - name: Run script
      run: python src/tools/extract_markdown_files.py
    - name: "Commit"
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update docs data.json
